// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXUCnAmLv9ilK7UtmLfPltoA4MSVesd4',
    appId: '1:1037445017430:web:7de5bae9c223d6350cf0f7',
    messagingSenderId: '1037445017430',
    projectId: 'vokapedia',
    authDomain: 'vokapedia.firebaseapp.com',
    storageBucket: 'vokapedia.firebasestorage.app',
    measurementId: 'G-K7PJZN90RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwSmsOEP08jJGOnx4-fDuqPB27dYWPkg',
    appId: '1:1037445017430:android:7d1f1ce5283c8f5e0cf0f7',
    messagingSenderId: '1037445017430',
    projectId: 'vokapedia',
    storageBucket: 'vokapedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yVPal-i5FD_-cLbLTEVZ1LNIlk0kiTE',
    appId: '1:1037445017430:ios:c8bf5eed3a8ccf950cf0f7',
    messagingSenderId: '1037445017430',
    projectId: 'vokapedia',
    storageBucket: 'vokapedia.firebasestorage.app',
    iosBundleId: 'com.example.vokapedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2yVPal-i5FD_-cLbLTEVZ1LNIlk0kiTE',
    appId: '1:1037445017430:ios:c8bf5eed3a8ccf950cf0f7',
    messagingSenderId: '1037445017430',
    projectId: 'vokapedia',
    storageBucket: 'vokapedia.firebasestorage.app',
    iosBundleId: 'com.example.vokapedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQXUCnAmLv9ilK7UtmLfPltoA4MSVesd4',
    appId: '1:1037445017430:web:da0b833849ef71270cf0f7',
    messagingSenderId: '1037445017430',
    projectId: 'vokapedia',
    authDomain: 'vokapedia.firebaseapp.com',
    storageBucket: 'vokapedia.firebasestorage.app',
    measurementId: 'G-TQGT1GCT8L',
  );
}
